name: Playwright Tests
on:
  push:
    branches: [ main, master, feature/APITest ]
  pull_request:
    branches: [ main, master, feature/APITest ]

     # schedule:
     - cron: '0 4 * * *' # Daily run at 04:00 AM UTC

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v5
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Install Allure Commandline
    - name: Install Allure CLI
      run: |
        npm i -D @playwright/test allure-playwright

    - name: Run Playwright Tests with Allure
      run: |
        npx playwright test 

    - name: Generate Allure Report
      if: ${{ always() }}
      run: |
       npx allure generate allure-results -o test-results/allure-report

    - name: Upload Allure Report Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
        retention-days: 30

    - name: Upload Playwright Report Artifact
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # OPTIONAL: Deploy Allure report to GitHub Pages (enable if needed)
    # - name: Deploy Allure Report to GitHub Pages
    #   if: ${{ always() }}
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: allure-report
