name: Playwright Tests

on:
    push:
    branches: [ main, master, feature/APITest ]
    pull_request:
    branches: [ main, master, feature/APITest ]

    schedule:
    - cron: '0 4 * * *' # Daily run at 04:00 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ðŸ‘‰ Allure CLI (if you use allure-commandline)
      - name: Install Allure commandline
        run: npm install -D allure-commandline

      # Run Playwright tests (Allure reporter must be enabled in playwright.config)
      - name: Run Playwright Tests
        run: npx playwright test

      # Generate Allure HTML report from allure-results
      - name: Generate Allure Report
        if: always()
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # Upload raw Allure results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # Upload Allure HTML report
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report